import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geist, jetBrainsMono } from "@/app/fonts";

export const metadata: Metadata = {
  title: "David Gracia's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${geistMono.variable} ${jetBrainsMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
