import type { Metadata } from "next";
import "./globals.css";
import {
  jetBrainsMono,
  notoSans,
  notoSansDisplay,
  notoSansMono,
} from "@/app/fonts";

export const metadata: Metadata = {
  title: "David Gracia's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${notoSansDisplay.variable} ${notoSansMono.variable} ${jetBrainsMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
